# Generated by Django 4.0.4 on 2022-07-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportshub', '0002_category_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportshub.category'),
        ),
    ]
