# Generated by Django 4.0.4 on 2022-07-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportshub', '0003_customer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='category',
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportshub.category'),
        ),
    ]
